### ISSUE TITLE
Error building on Lind Server

### ISSUE THREAD

**Issue by Yash151** [Lind-Project/lind_project#36] opened 2019-11-04 02:11 UTC
ENVIRONMENT USAGE REPORT
**********************************************************************
   4  dbg-linux-x86-64
   4  nacl-x86-64-pic-glibc
Done building NaCl
Building Repy in  to /home/lind/lind_project/lind/repy
'./seattlelib/xmlrpc_client.repy' -> '/home/lind/lind_project/lind/repy/repy/xmlrpc_client.repy'
'./seattlelib/xmlrpc_common.repy' -> '/home/lind/lind_project/lind/repy/repy/xmlrpc_common.repy'
'./seattlelib/xmlrpc_server.repy' -> '/home/lind/lind_project/lind/repy/repy/xmlrpc_server.repy'
Done building Repy in "/home/lind/lind_project/lind/repy/repy"
removed './lind_server.mix.new'

It's the same old story; boy meets beer, boy drinks beer... boy gets
another beer.
                -- Cheers

Copying component.h header to glibc:
Building glibc
make[1]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
make[1]: Entering directory '/home/lind/lind_project/src/native_client/tools'
Makefile:75: *** No suitable make binary found..  Stop.
make[1]: Leaving directory '/home/lind/lind_project/src/native_client/tools'

[./src/mklind:551] Error: [function: build_glibc()] [arguments: (nil)].

It took 55 seconds

All done.
make: *** [Makefile:8: all] Error 1

**Comment by rennergade** [comment] 2019-11-04 20:22
I've asked the IT admin to increase our disk space. I have a small suspicion that everything didn't get loaded because of lack of space. 

@neelchauhan and I are going to try and reproduce this once were upgraded. Hopefully this can be resolved soon...

**Comment by rennergade** [comment] 2019-11-06 21:05
@neelchauhan The diskspace has been upgraded on the server. Can you login and attempt to build lind?

**Comment by rennergade** [comment] 2019-11-11 21:53
So this is pretty weird, its failing at this point in the native client Makefile

```COMPAT_VER := $(shell $(MAKE_COMPAT) --version | sed -n '1 s/.* \([0-9]\)[0-9\.]*$$/\1/p')
COMPAT_VER := $(COMPAT_VER:4.%=)
ifeq ($(COMPAT_VER),)
       $(error No suitable make binary found.)
endif
```

But the make version is `4.21` and it's the same on my machine where it successfully builds. Not sure whats going on here.

**Comment by Yash151** [comment] 2019-11-15 00:43
In the start of the Makefile used for native client it says:
MAKE_VERSION is checked because we need to use the compat version if

**make is too new (versions after 4.x fail when building glibc32).**

`VERSION_TEST := $(MAKE_VERSION:4.%=)
ifeq ($(VERSION_TEST),)
	MAKE_COMPAT := $(shell find -H \
				/bin /sbin /usr/bin /usr/sbin \
					$HOME/bin $HOME/.local/bin \
				-mindepth 1 \
				-maxdepth 1 \
				-type f \
				-a \( \
					-name "make" \
					-o -name "make-[0-9]*" \
				\) \
				2>/dev/null \
				| sort \
				| tail -n1)
else
	MAKE_COMPAT := make
endif
ifeq ($(MAKE_COMPAT),)
       $(error No suitable make binary found.)
endif
COMPAT_VER := $(shell $(MAKE_COMPAT) --version | sed -n '1 s/.* \([0-9]\)[0-9\.]*$$/\1/p')
COMPAT_VER := $(COMPAT_VER:4.%=)
ifeq ($(COMPAT_VER),)
       $(error No suitable make binary found.)
endif`

So it should not work if the make version is 4.21

**Comment by rennergade** [comment] 2019-11-15 17:44
Ah! This seems like a good hint. You can see we include Make 3.82 [here](https://github.com/Lind-Project/lind_project/tree/d524e46ceda4b6acc7bd510a1569bf56a4f6e0c5/src/docker/base/home/lind/build/make-3.82). Which is in response to[ this older issue ](https://github.com/Lind-Project/lind_project/issues/2)that we haven't fixed yet.

It seems like make-3.82 either isn't building or isn't properly downloaded? I suggest you try to figure out why that's happening, and use make-3.82 (the updating make issue is pretty complicated and I hit a substantial roadlblock, this seems like lower hanging fruit to get us up and running!)

**Comment by rennergade** [comment] 2019-11-15 17:45
@jesings I think we ran into some issues with make when were trying to get this up this summer. Any ideas?

**Comment by rennergade** [comment] 2019-12-09 22:39
I'm going to close this for now as we're using our internal server.

**Closed by rennergade** 2019-12-09 22:39 UTC
