### ISSUE TITLE
Difference in Regular and Lind Output

### ISSUE THREAD

**Issue by kliu513** [Lind-Project/lind_project#100] opened 2020-09-21 22:29 UTC
I'm currently writing test files for the C programs, and I find that some of these programs perform very much differently within Lind as they run natively.

(1) dup2.c
This program is supposed to create and open a .txt file, duplicate its fd to stdout, write to the file, print a message to stdout directly, and eventually display the file contents via stdout. The program runs exactly as it should be within Lind. However, when it runs natively, the contents that are supposed to be written to the file **get printed out directly before the message**. I run `strace -f ./dup2` and find that the attempt to open the .txt file actually fails because of an EACCES (permission denied) error, which further results in an fd of -1 and failure of dup2().

(2) fork_simple.c
In this program, Process A forks and creates Process B, which then forks and creates Process C. Then Process A forks again and creates Process D. This program runs exactly as it should be in native, but Lind does not seem to do the right things. When the program runs within Lind, Process A forks and creates Process B, and then forks again and creates Process C. That's it. **The fourth process expected is never created.** Besides, the Lind output strangely **repeats itself** and is printed out twice. This is also not consistent with what is expected.

**Comment by rennergade** [comment] 2020-09-22 17:12
I just confirmed what you wrote here about both of these. Thanks for catching these errors.

1. For dup2.c, it seems I ignored native output when testing and just got it to do what I thought it should do. Bad work by me! There may be some file permission thing going on natively thats erroring while trying to create the initial file? That's just a guess.

What I think you should do here is debug the native version until it does what you'd expect the program to do, then run it in Lind to see if it matches, if not we'll have to change Lind's behavior. This should be a good and achievable project for you. Let me know if you get stuck anywhere.


2. This is a bit stranger. @jesings  it's probably worth you checking this out due to your work on both fork and getpid. This test isn't necessary perse, but we want to make sure both these things have the right behavior, especially fork!

**Comment by jesings** [comment] 2020-09-22 17:50
Getpid, in its current merged in form is perfectly functional, but just isn't handled by safePOSIX.
There may well be something going on in fork as there's a lot of machinery around it, but I'm not sure exactly what.

@kliu513 looking at the code for fork_simple.c, if I understand you correctly, the correct native output involves process 1 forking off process 2 which then forks of process 3 while process 1 forks off process 4. If I'm understanding you correctly, process 3, the grandchild of the original process, is never created. This may have to do with fork depth issues I'm working on currently, or it may not. In either case, do you know which, if any, forks are failing (returning -1)? Additionally can you show the full output of the lind process? It's great that you're finding things like these and it's bound to save us a whole lot of headaches in the future.

**Comment by kliu513** [comment] 2020-09-25 05:08
@jesings Below is the Lind output for the program:

@(1:52) $ lind /fork_simple.nexe                                                                                                                                                                                                                
executing: [sel_ldr -a -- "/lib/glibc/runnable-ld.so" --library-path "/lib/glibc" /fork_simple.nexe]                    
Lind v1.0-rc2                                                                                                           
Opening file system...                                                                                                  
done.                                                                                                                   
[1334,4229174336:18:36:53.080301] BYPASSING ALL ACL CHECKS                                                              
[#1:L17] pid 1 forking                                                                                                  
[#2:L39] pid = 1, ret = 2                                                                                               
[#3:L40] pid 1 forking again                                                                                            
[#4:L51] pid = 1, ret = 3                                                                                               
[#1:L17] pid 1 forking                                                                                                  
[#2:L39] pid = 1, ret = 2                                                                                               
[#3:L40] pid 1 forking again                                                                                            
[#4:L47] pid = 3, ret = 0                                                                                               
Persisting metadata: ...                                                                                                
Done persisting metadata.                                                                                               
Terminated

I just inspect how the program runs within Lind using high verbosity, and it seems that Lind is actually doing the right things with fork(), that is:
1 --> 2 --> 4
----> 3

None of the fork() syscalls fails, so the only thing Lind messes up is those print statements.

**Comment by rennergade** [comment] 2020-10-14 18:35
It seems like both of these issues are because of native/lind not exactly matching the execution order across processes, which really shouldn't be guaranteed anyways. What we should be doing is writing tests so these conflicts don't occur, either by not including output that could be effected by this or by writing programs in a way that ordering is guaranteed.

**Closed** 2020-10-14 18:35 UTC
