### ISSUE TITLE
Socketpair test

### ISSUE THREAD

**Issue by rennergade** [Lind-Project/lind_project#230] opened 2022-04-13 23:38 UTC
Socket Pair seems to deadlock (or more explicitly a close of a socket with a simultaneous read) on develop. I believe dashmap should resolve this.

I added a testcase to the branch `socketpairtest`. Let's test this out post dashmap merge and see if it works correctly. If so, lets add it to the test suite.

**Comment by justyoyo123** [comment] 2022-06-08 01:46
I tried to run this test but it is deadlocking.

**Comment by justyoyo123** [comment] 2022-08-10 21:28
The issue we found with socketpair is a concurrency issue where the sending sockobj needs to be closed to send the message but the read syscall on the receiving sockobj gets reached first. The sockobj read is a lock read so only other read syscalls can be done on the sockobj so when the parent tries to close and write to the sockobj, it cant due to the deadlocking caused by the read lock.  So the message was not sent and the read is left waiting for nothing.


Here: https://github.com/Lind-Project/safeposix-rust/blob/main/src/safeposix/syscalls/net_calls.rs at line 566 you'll see the read lock
Here: https://github.com/Lind-Project/safeposix-rust/blob/6d1e0d6e7963d2b7894c1a1f35e177f11c2ca7d7/src/safeposix/syscalls/fs_calls.rs at line 1272, you'll see the write to the sockobj

**Comment by jesings** [comment] 2023-01-15 19:32
**Rustposix shutdown issue**

Each socket file descriptor contains a reference to an underlying sockobj, which contains all of our non-fd-specific lind metadata about the socket as well as the actual native socket descriptor within it.
These sockobjs, in order to be safe, need to be rwlocked in rust, and there are other reasons why we might want this to be true (we do some checks for i.e. sockopt options, socket type. etc. on entry into the recv syscall, and don’t want those to be modified before or during the actual blocking syscall).
However, this causes an issue with shutdown, which is that while a sockobj is locked within a blocking recv call, we are unable to acquire rwlock around the sockobj for writing. This leads us to be entirely unable to shutdown these sockets, which is obviously not ok.
Closing is not a problem if we change sockobj cleanup to happen on the drop of an Arc rather than on the actual last close, which cleans some things up anyway.
The question then is how to solve this.
Do we unsafely access the socket’s inner contents in shutdown, opening us up to race conditions?
Do we actually recv with a timeout in a loop?
Do we figure out how to interrupt threads doing those blocking reads?
Do we try to lock the underlying native fd differently to the rest of the sockobj? This is also very fraught and would require unsafeness.

**Comment by rennergade** [comment] 2023-01-16 21:50
We're going to need to make blocking recv's timeout in a loop for cancellation to work properly. So if that also serves as a solution to this, that's great. If we do that can the rest of this be solved?

**Comment by rennergade** [comment] 2023-01-24 20:27
Finally fixed with the recent merge. @jesings can you also PR the socketpair test to lind_project? Then ill close this.

**Closed** 2023-01-30 02:12 UTC
